name: Azure Build and publish a Docker image
on:
  push:
    branches:
      - '*'

env:
    container_registry: devtoolhub
    IMAGE_NAME: azurecli
    SHA: ${{ github.event.after }}

jobs:
  build:
    name: Azure Build & push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: lint Action for Azure
        uses: hadolint/hadolint-action@v2.0.0
        with:
            dockerfile: azure/Dockerfile
            ignore: DL3018,SC2046,DL4006
            failure-threshold: warning
            no-color : false
            no-fail: true

      - name: Set short sha
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Azure Credentials 
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.container_registry }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}
      
      # - name: Docker build and push 
      #   run: |
      #     docker build . -t contoso.azurecr.io/k8sdemo:${{ github.sha }}
      #     docker push contoso.azurecr.io/k8sdemo:${{ github.sha }}

      - name: Build Docker image
        run: docker build . --file "azure/Dockerfile" --tag ${{ env.container_registry }}.azurecr.io/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        run: docker push ${{ env.container_registry }}.azurecr.io/${{ env.IMAGE_NAME }}

      - name: Run Trivy vulnerability scanner
        id: docker-scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.container_registry }}.azurecr.io/${{ env.IMAGE_NAME }}:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
